Exercise.create(title: "back extension")
Exercise.create(title: "bench press")
Exercise.create(title: "chest fly")
Exercise.create(title: "crunch")
Exercise.create(title: "dealift")
Exercise.create(title: "leg extensions")
Exercise.create(title: "leg press ")
Exercise.create(title: "leg raise")
Exercise.create(title: "preacher curl")
Exercise.create(title: "pull-ups")
Exercise.create(title: "push-ups")
Exercise.create(title: "shoulder fly")
Exercise.create(title: "shoulder press")
Exercise.create(title: "snatch")
Exercise.create(title: "squats")
Exercise.create(title: "upright row")
Exercise.create(title: "wall sits")